name: 打包（桌面）

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号
        required: true
      windows-console-mode:
        description: Nuitka-Action 的 windows-console-mode 参数值（disable 无控制台 / force 有控制台）
        required: true
        default: disable

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # cache: pnpm

      - name: 构建前端
        working-directory: frontend
        run: |
          pnpm install -g @quasar/cli
          pnpm install
          quasar build

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: 安装 Python 依赖
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: 构建可执行文件
        # https://github.com/Nuitka/Nuitka-Action/pull/73
        # 在合并之前暂时用这个
        uses: chenmozhijin/Nuitka-Action@main
        with:
          working-directory: backend
          nuitka-version: main
          script-name: src/main.py
          # 在 macOS 上使用 app 模式，不然每加载一个 *.so 都要给一次权限
          # 另一方面，这是 options-nanny 推荐的做法
          mode: ${{ runner.os == 'macOS' && 'app' || 'standalone' }}
          include-data-files: ../LICENSE=LICENSE
          include-data-dir: src/ui=ui
          output-file: GeometryCalculator
          product-name: 几何计算器
          file-description: 几何计算器
          macos-app-name: 几何计算器
          file-version: ${{ github.event.inputs.version }}
          macos-app-version: ${{ github.event.inputs.version }}
          copyright: 'Copyright (c) 2025 着火的冰块nya and contributors'
          windows-console-mode: ${{ github.event.inputs.windows-console-mode }}
          mingw64: true

      - name: 上传成果
        uses: actions/upload-artifact@v4
        with:
          name: GeometryCalculator-v${{ github.event.inputs.version }}-${{ runner.os }}
          path: |
            backend/build/main.dist/*
            backend/build/main.app/Contents/*
          include-hidden-files: true
